In [337]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [338]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [339]:
# Code for importing the csv file here. Since, separator is not explicitly stated, we will use sep = None and 
# allow Python to find the separator using builtin sniffer tool, csv.Sniffer. them ost common encoding is "ISO-8859-1"
movies =  pd.read_csv("./Data Set/Movie+Assignment+Data.csv", sep=None, encoding="ISO-8859-1")
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
11,Color,Bryan Singer,434.0,169.0,0.0,903.0,Marlon Brando,18000.0,200069408.0,Action|Adventure|Sci-Fi,...,2367.0,English,USA,PG-13,209000000.0,2006.0,10000.0,6.1,2.35,0
12,Color,Marc Forster,403.0,106.0,395.0,393.0,Mathieu Amalric,451.0,168368427.0,Action|Adventure,...,1243.0,English,UK,PG-13,200000000.0,2008.0,412.0,6.7,2.35,0
13,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
14,Color,Gore Verbinski,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000
15,Color,Zack Snyder,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
16,Color,Andrew Adamson,258.0,150.0,80.0,201.0,Pierfrancesco Favino,22000.0,141614023.0,Action|Adventure|Family|Fantasy,...,438.0,English,USA,PG,225000000.0,2008.0,216.0,6.6,2.35,0
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
18,Color,Rob Marshall,448.0,136.0,252.0,1000.0,Sam Claflin,40000.0,241063875.0,Action|Adventure|Fantasy,...,484.0,English,USA,PG-13,250000000.0,2011.0,11000.0,6.7,2.35,58000
19,Color,Barry Sonnenfeld,451.0,106.0,188.0,718.0,Michael Stuhlbarg,10000.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,341.0,English,USA,PG-13,225000000.0,2012.0,816.0,6.8,1.85,40000
20,Color,Peter Jackson,422.0,164.0,0.0,773.0,Adam Brown,5000.0,255108370.0,Adventure|Fantasy,...,802.0,English,New Zealand,PG-13,250000000.0,2014.0,972.0,7.5,2.35,65000
21,Color,Marc Webb,599.0,153.0,464.0,963.0,Andrew Garfield,15000.0,262030663.0,Action|Adventure|Fantasy,...,1225.0,English,USA,PG-13,230000000.0,2012.0,10000.0,7.0,2.35,56000
22,Color,Ridley Scott,343.0,156.0,0.0,738.0,William Hurt,891.0,105219735.0,Action|Adventure|Drama|History,...,546.0,English,USA,PG-13,200000000.0,2010.0,882.0,6.7,2.35,17000
23,Color,Peter Jackson,509.0,186.0,0.0,773.0,Adam Brown,5000.0,258355354.0,Adventure|Fantasy,...,951.0,English,USA,PG-13,225000000.0,2013.0,972.0,7.9,2.35,83000
24,Color,Chris Weitz,251.0,113.0,129.0,1000.0,Eva Green,16000.0,70083519.0,Adventure|Family|Fantasy,...,666.0,English,USA,PG-13,180000000.0,2007.0,6000.0,6.1,2.35,0
25,Color,Peter Jackson,446.0,201.0,0.0,84.0,Thomas Kretschmann,6000.0,218051260.0,Action|Adventure|Drama|Romance,...,2618.0,English,New Zealand,PG-13,207000000.0,2005.0,919.0,7.2,2.35,0
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
27,Color,Anthony Russo,516.0,147.0,94.0,11000.0,Scarlett Johansson,21000.0,407197282.0,Action|Adventure|Sci-Fi,...,1022.0,English,USA,PG-13,250000000.0,2016.0,19000.0,8.2,2.35,72000
28,Color,Peter Berg,377.0,131.0,532.0,627.0,Alexander SkarsgÃ¥rd,14000.0,65173160.0,Action|Adventure|Sci-Fi|Thriller,...,751.0,English,USA,PG-13,209000000.0,2012.0,10000.0,5.9,2.35,44000
29,Color,Colin Trevorrow,644.0,124.0,365.0,1000.0,Judy Greer,3000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,...,1290.0,English,USA,PG-13,150000000.0,2015.0,2000.0,7.0,2.00,150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5013,Color,Eric Eason,28.0,79.0,3.0,42.0,Panchito GÃ³mez,93.0,NaN,Drama|Family,...,21.0,English,USA,NaN,24000.0,2002.0,46.0,7.0,1.78,61
5014,Color,Uwe Boll,58.0,80.0,892.0,492.0,Katharine Isabelle,986.0,NaN,Action|Crime|Thriller,...,129.0,English,Canada,R,NaN,2009.0,918.0,6.3,2.35,0
5015,Black and White,Richard Linklater,61.0,100.0,0.0,0.0,Richard Linklater,5.0,1227508.0,Comedy|Drama,...,80.0,English,USA,R,23000.0,1991.0,0.0,7.1,1.37,2000
5016,Color,Joseph Mazzella,NaN,90.0,0.0,9.0,Mikaal Bates,313.0,NaN,Crime|Drama|Thriller,...,2.0,English,USA,NaN,25000.0,2015.0,25.0,4.8,NaN,33
5017,Color,Travis Legge,1.0,90.0,138.0,138.0,Suzi Lorraine,370.0,NaN,Comedy|Romance,...,3.0,English,USA,NaN,22000.0,2013.0,184.0,3.3,1.78,200
5018,Color,Alex Kendrick,5.0,120.0,589.0,4.0,Lisa Arnold,51.0,NaN,Drama,...,49.0,English,USA,NaN,20000.0,2003.0,49.0,6.9,1.85,725
5019,Color,Marcus Nispel,43.0,91.0,158.0,265.0,Brittany Curran,630.0,NaN,Horror|Mystery|Thriller,...,33.0,English,USA,R,NaN,2015.0,512.0,4.6,1.85,0
5020,NaN,Brandon Landers,NaN,143.0,8.0,8.0,Alana Kaniewski,720.0,NaN,Drama|Horror|Thriller,...,8.0,English,USA,NaN,17350.0,2011.0,19.0,3.0,NaN,33
5021,Color,Jay Duplass,51.0,85.0,157.0,10.0,Katie Aselton,830.0,192467.0,Comedy|Drama|Romance,...,71.0,English,USA,R,15000.0,2005.0,224.0,6.6,NaN,297
5022,Black and White,Jim Chuchu,6.0,60.0,0.0,4.0,Olwenya Maina,147.0,NaN,Drama,...,1.0,Swahili,Kenya,NaN,15000.0,2014.0,19.0,7.4,NaN,45
5023,Color,Daryl Wein,22.0,88.0,38.0,211.0,Heather Burns,331.0,76382.0,Romance,...,8.0,English,USA,NaN,15000.0,2009.0,212.0,6.2,2.35,324
5024,Color,Jason Trost,42.0,78.0,91.0,86.0,Jason Trost,407.0,NaN,Sci-Fi|Thriller,...,35.0,English,USA,Unrated,20000.0,2011.0,91.0,4.0,2.35,835
5025,Color,John Waters,73.0,108.0,0.0,105.0,Mink Stole,462.0,180483.0,Comedy|Crime|Horror,...,183.0,English,USA,NC-17,10000.0,1972.0,143.0,6.1,1.37,0
5026,Color,Olivier Assayas,81.0,110.0,107.0,45.0,BÃ©atrice Dalle,576.0,136007.0,Drama|Music|Romance,...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171
5027,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,26.0,Persian,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697
5028,Black and White,Ivan Kavanagh,12.0,83.0,18.0,0.0,Michael Parle,10.0,NaN,Horror,...,1.0,English,Ireland,NaN,10000.0,2007.0,5.0,6.7,1.33,105
5029,Color,Kiyoshi Kurosawa,78.0,111.0,62.0,6.0,Anna Nakagawa,89.0,94596.0,Crime|Horror|Mystery|Thriller,...,50.0,Japanese,Japan,NaN,1000000.0,1997.0,13.0,7.4,1.85,817
5030,Color,Tadeo Garcia,NaN,84.0,5.0,12.0,Michael Cortez,21.0,NaN,Drama,...,3.0,English,USA,NaN,NaN,2004.0,20.0,6.1,NaN,22
5031,Color,Thomas L. Phillips,13.0,82.0,120.0,84.0,Joe Coffey,785.0,NaN,Comedy|Horror|Thriller,...,8.0,English,USA,NaN,200000.0,2012.0,98.0,5.4,16.00,424
5032,Color,Ash Baron-Cohen,10.0,98.0,3.0,152.0,Stanley B. Herman,789.0,NaN,Crime|Drama,...,14.0,English,USA,NaN,NaN,1995.0,194.0,6.4,NaN,20
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
5034,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
5036,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
5037,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [340]:
print ("The various columns of movies database are:- \n" ,movies.columns.values)
print ("\nThe shape of the movies dataframe is :- \n No of rows = ", movies.shape[0], "\n No of columns = ",movies.shape[1]) 
print ("\n Information about movies dataFrame including the index dtype and column dtypes, non-null values and memory usage:- ")
print (movies.info())
print ("\nThe descriptive statistics that summarize the central tendency, dispersion and shape of a dataset’s distribution, excluding NaN values.- \n",movies.describe())

The various columns of movies database are:-
 ['color' 'director_name' 'num_critic_for_reviews' 'duration'
 'director_facebook_likes' 'actor_3_facebook_likes' 'actor_2_name'
 'actor_1_facebook_likes' 'gross' 'genres' 'actor_1_name' 'movie_title'
 'num_voted_users' 'cast_total_facebook_likes' 'actor_3_name'
 'facenumber_in_poster' 'plot_keywords' 'movie_imdb_link'
 'num_user_for_reviews' 'language' 'country' 'content_rating' 'budget'
 'title_year' 'actor_2_facebook_likes' 'imdb_score' 'aspect_ratio'
 'movie_facebook_likes']

The shape of the movies dataframe is :-
 No of rows =  5043
 No of columns =  28

 Information about movies dataFrame including the index dtype and column dtypes, non-null values and memory usage:-
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
color                        5024 non-null object
director_name                4939 non-null object
num_critic_for_reviews       4993 non-null float64
duration                     5028 non-null float64
director_facebook_likes      4939 non-null float64
actor_3_facebook_likes       5020 non-null float64
actor_2_name                 5030 non-null object
actor_1_facebook_likes       5036 non-null float64
gross                        4159 non-null float64
genres                       5043 non-null object
actor_1_name                 5036 non-null object
movie_title                  5043 non-null object
num_voted_users              5043 non-null int64
cast_total_facebook_likes    5043 non-null int64
actor_3_name                 5020 non-null object
facenumber_in_poster         5030 non-null float64
plot_keywords                4890 non-null object
movie_imdb_link              5043 non-null object
num_user_for_reviews         5022 non-null float64
language                     5031 non-null object
country                      5038 non-null object
content_rating               4740 non-null object
budget                       4551 non-null float64
title_year                   4935 non-null float64
actor_2_facebook_likes       5030 non-null float64
imdb_score                   5043 non-null float64
aspect_ratio                 4714 non-null float64
movie_facebook_likes         5043 non-null int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB
None

The descriptive statistics that summarize the central tendency, dispersion and shape of a dataset’s distribution, excluding NaN values.-
        num_critic_for_reviews     duration  director_facebook_likes  \
count             4993.000000  5028.000000              4939.000000
mean               140.194272   107.201074               686.509212
std                121.601675    25.197441              2813.328607
min                  1.000000     7.000000                 0.000000
25%                 50.000000    93.000000                 7.000000
50%                110.000000   103.000000                49.000000
75%                195.000000   118.000000               194.500000
max                813.000000   511.000000             23000.000000

       actor_3_facebook_likes  actor_1_facebook_likes         gross  \
count             5020.000000             5036.000000  4.159000e+03
mean               645.009761             6560.047061  4.846841e+07
std               1665.041728            15020.759120  6.845299e+07
min                  0.000000                0.000000  1.620000e+02
25%                133.000000              614.000000  5.340988e+06
50%                371.500000              988.000000  2.551750e+07
75%                636.000000            11000.000000  6.230944e+07
max              23000.000000           640000.000000  7.605058e+08

       num_voted_users  cast_total_facebook_likes  facenumber_in_poster  \
count     5.043000e+03                5043.000000           5030.000000
mean      8.366816e+04                9699.063851              1.371173
std       1.384853e+05               18163.799124              2.013576
min       5.000000e+00                   0.000000              0.000000
25%       8.593500e+03                1411.000000              0.000000
50%       3.435900e+04                3090.000000              1.000000
75%       9.630900e+04               13756.500000              2.000000
max       1.689764e+06              656730.000000             43.000000

       num_user_for_reviews        budget   title_year  \
count           5022.000000  4.551000e+03  4935.000000
mean             272.770808  3.975262e+07  2002.470517
std              377.982886  2.061149e+08    12.474599
min                1.000000  2.180000e+02  1916.000000
25%               65.000000  6.000000e+06  1999.000000
50%              156.000000  2.000000e+07  2005.000000
75%              326.000000  4.500000e+07  2011.000000
max             5060.000000  1.221550e+10  2016.000000

       actor_2_facebook_likes   imdb_score  aspect_ratio  movie_facebook_likes
count             5030.000000  5043.000000   4714.000000           5043.000000
mean              1651.754473     6.442138      2.220403           7525.964505
std               4042.438863     1.125116      1.385113          19320.445110
min                  0.000000     1.600000      1.180000              0.000000
25%                281.000000     5.800000      1.850000              0.000000
50%                595.000000     6.600000      2.350000            166.000000
75%                918.000000     7.200000      2.350000           3000.000000
max             137000.000000     9.500000     16.000000         349000.000000

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [341]:
# Code for column-wise null count. The isnull() function finds the rows ( axis =0 ) as null for columns and sum() 
# function sums up row values for each column 
print(movies.isnull().sum(axis=0))

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [342]:
# Code for row-wise null count. The isnull() function finds the columns( axis =1 )  with  value as null for rows and sum() 
# function sums up column values for each row 
print(movies.isnull().sum(axis=1))

0        0
1        0
2        0
3        0
4       14
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
5013     2
5014     2
5015     0
5016     5
5017     2
5018     2
5019     2
5020     5
5021     1
5022     4
5023     2
5024     1
5025     0
5026     0
5027     0
5028     3
5029     1
5030     5
5031     3
5032     4
5033     0
5034     1
5035     0
5036     3
5037     1
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [343]:
# Code for calculating column-wise null percentages. 
# The percentage of null columns = 100 *( no of null columns)/(no of total columns)
# round function is used to round-off the percentage. Here, 2 stands for the precision digits for round-off
print(round(100*(movies.isnull().sum()/len(movies.index)), 2))

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.24
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [344]:
# Code for dropping the columns here.
# drop function takes the column name as input and drops that column
# axis=1 means columns
movies = movies.drop('color', axis=1)
movies = movies.drop('director_facebook_likes', axis=1)
movies = movies.drop('actor_1_facebook_likes', axis=1)
movies = movies.drop('actor_2_facebook_likes', axis=1)
movies = movies.drop('actor_3_facebook_likes', axis=1)
movies = movies.drop('actor_2_name', axis=1)
movies = movies.drop('cast_total_facebook_likes', axis=1)
movies = movies.drop('actor_3_name', axis=1)
movies = movies.drop('duration', axis=1)
movies = movies.drop('facenumber_in_poster', axis=1)
movies = movies.drop('content_rating', axis=1)
movies = movies.drop('country', axis=1)
movies = movies.drop('movie_imdb_link', axis=1)
movies = movies.drop('aspect_ratio', axis=1)
movies = movies.drop('plot_keywords', axis=1)

rounded_off_rem_percent_of_nulls_in_each_column = round(100*(movies.isnull().sum()/len(movies.index)), 2)
print(rounded_off_rem_percent_of_nulls_in_each_column )

director_name              2.06
num_critic_for_reviews     0.99
gross                     17.53
genres                     0.00
actor_1_name               0.14
movie_title                0.00
num_voted_users            0.00
num_user_for_reviews       0.42
language                   0.24
budget                     9.76
title_year                 2.14
imdb_score                 0.00
movie_facebook_likes       0.00
dtype: float64

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [345]:
# Code for dropping the rows here
# On inspection we found that gross and budget columns had large no of null values
# So, we are slicing of the null vlaues for both these columns isnan check if the value is NaN and
# ~ ensures the reverse of the conition i.e. columns with non-NaN values are discarded from data frame
movies =  movies[~np.isnan(movies['gross'])]
movies =  movies[~np.isnan(movies['budget'])]
print(round(100*(movies.isnull().sum()/len(movies.index)), 2))

director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.08
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.08
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [346]:
# Code for dropping rows that have greater than five NaN values
# isnull() returns the rows with null values for column and sum() funciton gets us the count of such rows
# The condition less than 5 ensures we select only those rows with <5 nulls for columns
movies = movies[movies.isnull().sum(axis=1) <= 5]
print(round(100*(movies.isnull().sum()/len(movies.index)), 2))

director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.08
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.08
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [347]:
# Code for filling the NaN values in the 'language' column 
# Below code will find all rows that have language column as Nan and 
# replace those NaN values with 'English'
movies.loc[pd.isnull(movies['language']), ['language']] = 'English'
print(round(100*(movies.isnull().sum()/len(movies.index)), 2))

director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.08
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.00
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [348]:
# shape[0] tells us the no of rows retained after cleaning the data in above steps
print(movies.shape[0])
# The initial number of rows that we had was 5043
# So, remaininng rows percentage = 100 * (No of rows present after cleaning the data) / 5043 
print(100*len(movies.index)/5043)

3891
77.15645449137418

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [349]:
# The current unit of budget and gross is $. Dividing by 10,00,000 will gives us values in millions
# The nanonymous lambda function divides each value by 1 million and converts the values into million dollars
movies['budget'] = movies['budget'].apply(lambda x: x/1000000)
movies['gross'] = movies['gross'].apply(lambda x: x/1000000)

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [350]:
# Code for creating the profit column here
# Profit = Gross Earnings - Budget for making movies
# The below code will create a new column 'profit' and calculate its value by subtracting the value in gross column
# with value in budget column
movies['profit'] = movies['gross'] - movies['budget']
print(movies.head(10))

        director_name  num_critic_for_reviews       gross  \
0       James Cameron                   723.0  760.505847
1      Gore Verbinski                   302.0  309.404152
2          Sam Mendes                   602.0  200.074175
3   Christopher Nolan                   813.0  448.130642
5      Andrew Stanton                   462.0   73.058679
6           Sam Raimi                   392.0  336.530303
7        Nathan Greno                   324.0  200.807262
8         Joss Whedon                   635.0  458.991599
9         David Yates                   375.0  301.956980
10        Zack Snyder                   673.0  330.249062

                                               genres     actor_1_name  \
0                     Action|Adventure|Fantasy|Sci-Fi      CCH Pounder
1                            Action|Adventure|Fantasy      Johnny Depp
2                           Action|Adventure|Thriller  Christoph Waltz
3                                     Action|Thriller        Tom Hardy
5                             Action|Adventure|Sci-Fi     Daryl Sabara
6                            Action|Adventure|Romance     J.K. Simmons
7   Adventure|Animation|Comedy|Family|Fantasy|Musi...     Brad Garrett
8                             Action|Adventure|Sci-Fi  Chris Hemsworth
9                    Adventure|Family|Fantasy|Mystery     Alan Rickman
10                            Action|Adventure|Sci-Fi     Henry Cavill

                                   movie_title  num_voted_users  \
0                                     AvatarÂ            886204
1   Pirates of the Caribbean: At World's EndÂ            471220
2                                    SpectreÂ            275868
3                      The Dark Knight RisesÂ           1144337
5                                John CarterÂ            212204
6                               Spider-Man 3Â            383056
7                                    TangledÂ            294810
8                    Avengers: Age of UltronÂ            462669
9     Harry Potter and the Half-Blood PrinceÂ            321795
10        Batman v Superman: Dawn of JusticeÂ            371639

    num_user_for_reviews language  budget  title_year  imdb_score  \
0                 3054.0  English   237.0      2009.0         7.9
1                 1238.0  English   300.0      2007.0         7.1
2                  994.0  English   245.0      2015.0         6.8
3                 2701.0  English   250.0      2012.0         8.5
5                  738.0  English   263.7      2012.0         6.6
6                 1902.0  English   258.0      2007.0         6.2
7                  387.0  English   260.0      2010.0         7.8
8                 1117.0  English   250.0      2015.0         7.5
9                  973.0  English   250.0      2009.0         7.5
10                3018.0  English   250.0      2016.0         6.9

    movie_facebook_likes      profit
0                  33000  523.505847
1                      0    9.404152
2                  85000  -44.925825
3                 164000  198.130642
5                  24000 -190.641321
6                      0   78.530303
7                  29000  -59.192738
8                 118000  208.991599
9                  10000   51.956980
10                197000   80.249062

In [351]:
# Code for sorting the dataframe
# The sort_values() function when used with a data frame sorts the data frame rows according to the column
# specified with 'by' parameter. ascending = False means it will osrt in descending order. 
movies = movies.sort_values(by=['profit'],ascending=False)
print(movies.head())

         director_name  num_critic_for_reviews       gross  \
0        James Cameron                   723.0  760.505847
29     Colin Trevorrow                   644.0  652.177271
26       James Cameron                   315.0  658.672302
3024      George Lucas                   282.0  460.935665
3080  Steven Spielberg                   215.0  434.949459

                                genres         actor_1_name  \
0      Action|Adventure|Fantasy|Sci-Fi          CCH Pounder
29    Action|Adventure|Sci-Fi|Thriller  Bryce Dallas Howard
26                       Drama|Romance    Leonardo DiCaprio
3024   Action|Adventure|Fantasy|Sci-Fi        Harrison Ford
3080                     Family|Sci-Fi         Henry Thomas

                               movie_title  num_voted_users  \
0                                 AvatarÂ            886204
29                        Jurassic WorldÂ            418214
26                               TitanicÂ            793059
3024  Star Wars: Episode IV - A New HopeÂ            911097
3080          E.T. the Extra-TerrestrialÂ            281842

      num_user_for_reviews language  budget  title_year  imdb_score  \
0                   3054.0  English   237.0      2009.0         7.9
29                  1290.0  English   150.0      2015.0         7.0
26                  2528.0  English   200.0      1997.0         7.7
3024                1470.0  English    11.0      1977.0         8.7
3080                 515.0  English    10.5      1982.0         7.9

      movie_facebook_likes      profit
0                    33000  523.505847
29                  150000  502.177271
26                   26000  458.672302
3024                 33000  449.935665
3080                 34000  424.449459

In [352]:
# Code to get the top 10 profiting movies 
# Since in the previous steps we have already introduced a column profit, assigned it appropriate values
# and sorted data frame according to profit column, the top 10 values for 'movie_title' will gives us the top
# 10 profiting movies. To get the top 10 values, we use the head() function with parameter '10'.
top10 = movies.head(10)['movie_title']
print(top10)

0                                          AvatarÂ
29                                 Jurassic WorldÂ
26                                        TitanicÂ
3024           Star Wars: Episode IV - A New HopeÂ
3080                   E.T. the Extra-TerrestrialÂ
794                                  The AvengersÂ
17                                   The AvengersÂ
509                                 The Lion KingÂ
240     Star Wars: Episode I - The Phantom MenaceÂ
66                                The Dark KnightÂ
Name: movie_title, dtype: object

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [353]:
# In the top 10 values that we got usingh ead function, we can see that we got duplicate value for The Avengers
# As per the subtaks requirement we will remove the duplicate values using drop_duplicates() function.
# The inplace=True signifies that the same data frame will be modified to reflect the modifications and any new
# data frame will not be returned
movies.drop_duplicates(inplace=True)
print(movies.head(10)['movie_title'])

0                                          AvatarÂ
29                                 Jurassic WorldÂ
26                                        TitanicÂ
3024           Star Wars: Episode IV - A New HopeÂ
3080                   E.T. the Extra-TerrestrialÂ
794                                  The AvengersÂ
509                                 The Lion KingÂ
240     Star Wars: Episode I - The Phantom MenaceÂ
66                                The Dark KnightÂ
439                              The Hunger GamesÂ
Name: movie_title, dtype: object

In [354]:
# As per the requirement, we will try to again fetch the top 10 movies
top10 = movies.head(10)['movie_title']
print(top10)
# In the below result you can see Avatar amd Titanic are two films directed by James Cameron

0                                          AvatarÂ
29                                 Jurassic WorldÂ
26                                        TitanicÂ
3024           Star Wars: Episode IV - A New HopeÂ
3080                   E.T. the Extra-TerrestrialÂ
794                                  The AvengersÂ
509                                 The Lion KingÂ
240     Star Wars: Episode I - The Phantom MenaceÂ
66                                The Dark KnightÂ
439                              The Hunger GamesÂ
Name: movie_title, dtype: object

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [355]:
# Code for extracting the top 250 movies as per the IMDb score 
# We will first of all filter out the movies that have less than number of voted users, then sort the values of movies
# and then get the Top 250 movies from the list based on their imdb_score or rating
# We will store the result in new data frame called 'IMDb_Top_250'
IMDb_Top_250 = movies.loc[movies['num_voted_users'] > 25000].sort_values(by=['imdb_score'],ascending=False).head(250)

# We will create a new column Rank that will contain the ranking of the movies by imdb_score.
# Since the above list is already sorted based on imdb_score, we can safely assigning the rank column
# range of values from 1 to 250. The value 251 is boundary value and is excluded
IMDb_Top_250['Rank'] = np.arange(1,251)

# For having a better view of data we will set 'Rank' as the index
IMDb_Top_250.set_index("Rank", inplace = True)

In [356]:
# As per the task requirement, we will write code to extract top foreign language films from 'IMDb_Top_250'
# In order to find foreign language film we will chose the films in IMDb_Top_250 that donot have there language
# as English
Top_Foreign_Lang_Film = IMDb_Top_250.loc[(IMDb_Top_250.language != 'English'), :]

# In the below data frame we can see Veer-Zaara is a part of Foreign Language films
print (Top_Foreign_Lang_Film.loc[Top_Foreign_Lang_Film.movie_title == 'Veer-ZaaraÂ '])

     director_name  num_critic_for_reviews     gross                 genres  \
Rank
227    Yash Chopra                    29.0  2.921738  Drama|Musical|Romance

        actor_1_name   movie_title  num_voted_users  num_user_for_reviews  \
Rank
227   Shah Rukh Khan  Veer-ZaaraÂ             34449                 119.0

     language  budget  title_year  imdb_score  movie_facebook_likes    profit
Rank
227     Hindi     7.0      2004.0         7.9                  2000 -4.078262

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [357]:
# Code for extracting the top 10 directors here
# We will create a temporary variable to find the mean value of imdb_score for various directors
df_grpby_dirname = movies.groupby('director_name').imdb_score.mean()

# Then we will sort the obtained group in descending order of imdb_score and store it in df_grpby_dirname_sorted 
df_grpby_dirname_sorted = df_grpby_dirname.sort_values(ascending=False)

# Lastly we will pick the Top 10 directors by choosing the Top 10 values using head from the sorted list
top10director = df_grpby_dirname_sorted.head(10)
print(top10director)
# As you can see below Damien Chazelle is in the list

director_name
Charles Chaplin      8.600000
Tony Kaye            8.600000
Ron Fricke           8.500000
Damien Chazelle      8.500000
Majid Majidi         8.500000
Alfred Hitchcock     8.500000
Sergio Leone         8.433333
Christopher Nolan    8.425000
Asghar Farhadi       8.400000
Richard Marquand     8.400000
Name: imdb_score, dtype: float64

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [358]:
# Code for extracting the first two genres of each movie here
# The apply() function is used to apply a function repeatedly over a given series.

# Inorder to find the genre_1, for each row  we will split the existing genres column value
# using separator '|' and take the first substring obtained
movies['genre_1'] = movies['genres'].apply(lambda x: x.split('|')[0] )

# Inorder to find the genre_2, for each row  we will split the existing genres column value
# using separator '|' and take the second substring obtained if available or use the first substring
# if not available and insert it into 'genre_2' column
movies['genre_2'] = movies['genres'].apply(lambda x: x.split('|')[1] if len(x.split('|')) > 1 else x.split('|')[0] )
print(movies.head(50))

# As you can see, for movie Hangover which had only one 'genres' value 'Comedy', both 'genre_1' and 'genre_2'
# are comedy.

           director_name  num_critic_for_reviews       gross  \
0          James Cameron                   723.0  760.505847
29       Colin Trevorrow                   644.0  652.177271
26         James Cameron                   315.0  658.672302
3024        George Lucas                   282.0  460.935665
3080    Steven Spielberg                   215.0  434.949459
794          Joss Whedon                   703.0  623.279547
509         Roger Allers                   186.0  422.783777
240         George Lucas                   320.0  474.544677
66     Christopher Nolan                   645.0  533.316061
439            Gary Ross                   673.0  407.999255
812           Tim Miller                   579.0  363.024263
186     Francis Lawrence                   502.0  424.645577
697     Steven Spielberg                   308.0  356.784000
521        Pierre Coffin                   306.0  368.049635
814       Clint Eastwood                   490.0  350.123553
338       Andrew Stanton                   301.0  380.838870
582       Andrew Adamson                   205.0  436.471036
339        Peter Jackson                   328.0  377.019252
1536    Richard Marquand                   197.0  309.125409
836      Robert Zemeckis                   149.0  329.691196
2051      Irvin Kershner                   223.0  290.158751
2601      Chris Columbus                   102.0  285.761243
236         George Lucas                   359.0  380.262555
161            Sam Raimi                   291.0  403.706375
563           Kyle Balda                   308.0  336.029560
1181  M. Night Shyamalan                   234.0  293.501675
2917    Steven Spielberg                   385.0  260.000000
125           Chris Buck                   406.0  400.736600
519        Yarrow Cheney                   165.0  323.505540
926          Chris Weitz                   299.0  296.623634
340        Peter Jackson                   294.0  340.478898
1397       Todd Phillips                   334.0  277.313371
3737          Joel Zwick                   168.0  241.437427
631          David Slade                   293.0  300.523113
522      Roland Emmerich                   185.0  306.124059
1403    John Lee Hancock                   261.0  255.950375
2152    Steven Spielberg                   234.0  242.374454
270        Peter Jackson                   297.0  313.837577
2600        Martin Brest                    94.0  234.760500
1400          Tim Burton                   186.0  251.188924
43           Lee Unkrich                   453.0  414.984497
207     Francis Lawrence                   403.0  337.103873
32           Shane Black                   608.0  408.992272
8            Joss Whedon                   635.0  458.991599
927       Andrew Adamson                   212.0  267.652016
36           Michael Bay                   366.0  402.076689
710            Jay Roach                   141.0  279.167575
3      Christopher Nolan                   813.0  448.130642
13        Gore Verbinski                   313.0  423.032628
767            Phil Lord                   435.0  257.756197

                                                 genres         actor_1_name  \
0                       Action|Adventure|Fantasy|Sci-Fi          CCH Pounder
29                     Action|Adventure|Sci-Fi|Thriller  Bryce Dallas Howard
26                                        Drama|Romance    Leonardo DiCaprio
3024                    Action|Adventure|Fantasy|Sci-Fi        Harrison Ford
3080                                      Family|Sci-Fi         Henry Thomas
794                             Action|Adventure|Sci-Fi      Chris Hemsworth
509            Adventure|Animation|Drama|Family|Musical    Matthew Broderick
240                     Action|Adventure|Fantasy|Sci-Fi      Natalie Portman
66                          Action|Crime|Drama|Thriller       Christian Bale
439                     Adventure|Drama|Sci-Fi|Thriller    Jennifer Lawrence
812              Action|Adventure|Comedy|Romance|Sci-Fi        Ryan Reynolds
186                           Adventure|Sci-Fi|Thriller    Jennifer Lawrence
697                           Adventure|Sci-Fi|Thriller         Wayne Knight
521                      Animation|Comedy|Family|Sci-Fi         Steve Carell
814         Action|Biography|Drama|History|Thriller|War       Bradley Cooper
338                   Adventure|Animation|Comedy|Family      Alexander Gould
582   Adventure|Animation|Comedy|Family|Fantasy|Romance       Rupert Everett
339                      Action|Adventure|Drama|Fantasy        Orlando Bloom
1536                    Action|Adventure|Fantasy|Sci-Fi        Harrison Ford
836                                        Comedy|Drama            Tom Hanks
2051                    Action|Adventure|Fantasy|Sci-Fi        Harrison Ford
2601                                      Comedy|Family      Macaulay Culkin
236                     Action|Adventure|Fantasy|Sci-Fi      Natalie Portman
161                    Action|Adventure|Fantasy|Romance         J.K. Simmons
563               Action|Animation|Comedy|Family|Sci-Fi         Steve Carell
1181                             Drama|Mystery|Thriller         Bruce Willis
2917                           Adventure|Drama|Thriller         Roy Scheider
125   Adventure|Animation|Comedy|Family|Fantasy|Musical             Josh Gad
519                             Animation|Comedy|Family         Steve Coogan
926                     Adventure|Drama|Fantasy|Romance     Robert Pattinson
340                      Action|Adventure|Drama|Fantasy      Christopher Lee
1397                                             Comedy       Bradley Cooper
3737                              Comedy|Family|Romance         Nia Vardalos
631                     Adventure|Drama|Fantasy|Romance     Robert Pattinson
522                             Action|Adventure|Sci-Fi           Will Smith
1403                              Biography|Drama|Sport       Catherine Dyer
2152                                   Action|Adventure        Harrison Ford
270                      Action|Adventure|Drama|Fantasy      Christopher Lee
2600                                Action|Comedy|Crime       Judge Reinhold
1400                                   Action|Adventure        Michael Gough
43            Adventure|Animation|Comedy|Family|Fantasy            Tom Hanks
207                           Adventure|Sci-Fi|Thriller    Jennifer Lawrence
32                              Action|Adventure|Sci-Fi    Robert Downey Jr.
8                               Action|Adventure|Sci-Fi      Chris Hemsworth
927           Adventure|Animation|Comedy|Family|Fantasy     Kathleen Freeman
36                              Action|Adventure|Sci-Fi      Glenn Morshower
710                                      Comedy|Romance       Robert De Niro
3                                       Action|Thriller            Tom Hardy
13                             Action|Adventure|Fantasy          Johnny Depp
767    Action|Adventure|Animation|Comedy|Family|Fantasy       Morgan Freeman

                                            movie_title  num_voted_users  \
0                                              AvatarÂ            886204
29                                     Jurassic WorldÂ            418214
26                                            TitanicÂ            793059
3024               Star Wars: Episode IV - A New HopeÂ            911097
3080                       E.T. the Extra-TerrestrialÂ            281842
794                                      The AvengersÂ            995415
509                                     The Lion KingÂ            644348
240         Star Wars: Episode I - The Phantom MenaceÂ            534658
66                                    The Dark KnightÂ           1676169
439                                  The Hunger GamesÂ            701607
812                                          DeadpoolÂ            479047
186                   The Hunger Games: Catching FireÂ            498397
697                                     Jurassic ParkÂ            613473
521                                   Despicable Me 2Â            286877
814                                   American SniperÂ            325264
338                                      Finding NemoÂ            692482
582                                           Shrek 2Â            314630
339     The Lord of the Rings: The Return of the KingÂ           1215718
1536       Star Wars: Episode VI - Return of the JediÂ            681857
836                                      Forrest GumpÂ           1251222
2051   Star Wars: Episode V - The Empire Strikes BackÂ            837759
2601                                       Home AloneÂ            311075
236      Star Wars: Episode III - Revenge of the SithÂ            520104
161                                        Spider-ManÂ            544665
563                                           MinionsÂ            142403
1181                                  The Sixth SenseÂ            704766
2917                                             JawsÂ            412454
125                                            FrozenÂ            421658
519                           The Secret Life of PetsÂ             24407
926                       The Twilight Saga: New MoonÂ            220758
340             The Lord of the Rings: The Two TowersÂ           1100446
1397                                     The HangoverÂ            583341
3737                         My Big Fat Greek WeddingÂ            102071
631                        The Twilight Saga: EclipseÂ            184637
522                                  Independence DayÂ            430055
1403                                   The Blind SideÂ            223127
2152                          Raiders of the Lost ArkÂ            661017
270   The Lord of the Rings: The Fellowship of the R...          1238746
2600                                Beverly Hills CopÂ            126464
1400                                           BatmanÂ            269033
43                                        Toy Story 3Â            544884
207             The Hunger Games: Mockingjay - Part 1Â            305008
32                                         Iron Man 3Â            557489
8                             Avengers: Age of UltronÂ            462669
927                                             ShrekÂ            467113
36                Transformers: Revenge of the FallenÂ            323207
710                                  Meet the FockersÂ            211296
3                               The Dark Knight RisesÂ           1144337
13         Pirates of the Caribbean: Dead Man's ChestÂ            522040
767                                    The Lego MovieÂ            246698

      num_user_for_reviews language  budget  title_year  imdb_score  \
0                   3054.0  English   237.0      2009.0         7.9
29                  1290.0  English   150.0      2015.0         7.0
26                  2528.0  English   200.0      1997.0         7.7
3024                1470.0  English    11.0      1977.0         8.7
3080                 515.0  English    10.5      1982.0         7.9
794                 1722.0  English   220.0      2012.0         8.1
509                  656.0  English    45.0      1994.0         8.5
240                 3597.0  English   115.0      1999.0         6.5
66                  4667.0  English   185.0      2008.0         9.0
439                 1959.0  English    78.0      2012.0         7.3
812                 1058.0  English    58.0      2016.0         8.1
186                  706.0  English   130.0      2013.0         7.6
697                  895.0  English    63.0      1993.0         8.1
521                  284.0  English    76.0      2013.0         7.5
814                  916.0  English    58.8      2014.0         7.3
338                  866.0  English    94.0      2003.0         8.2
582                  483.0  English   150.0      2004.0         7.2
339                 3189.0  English    94.0      2003.0         8.9
1536                 647.0  English    32.5      1983.0         8.4
836                 1398.0  English    55.0      1994.0         8.8
2051                 900.0  English    18.0      1980.0         8.8
2601                 305.0  English    18.0      1990.0         7.5
236                 3286.0  English   113.0      2005.0         7.6
161                 2012.0  English   139.0      2002.0         7.3
563                  275.0  English    74.0      2015.0         6.4
1181                2073.0  English    40.0      1999.0         8.1
2917                 962.0  English     8.0      1975.0         8.0
125                  904.0  English   150.0      2013.0         7.6
519                  155.0  English    75.0      2016.0         6.8
926                  919.0  English    50.0      2009.0         4.6
340                 2417.0  English    94.0      2002.0         8.7
1397                 626.0  English    35.0      2009.0         7.8
3737                 756.0  English     5.0      2002.0         6.6
631                  498.0  English    68.0      2010.0         4.9
522                  856.0  English    75.0      1996.0         6.9
1403                 420.0  English    29.0      2009.0         7.7
2152                 771.0  English    18.0      1981.0         8.5
270                 5060.0  English    93.0      2001.0         8.8
2600                 175.0  English    14.0      1984.0         7.3
1400                 817.0  English    35.0      1989.0         7.6
43                   733.0  English   200.0      2010.0         8.3
207                  591.0  English   125.0      2014.0         6.7
32                  1187.0  English   200.0      2013.0         7.2
8                   1117.0  English   250.0      2015.0         7.5
927                  945.0  English    60.0      2001.0         7.9
36                  1439.0  English   200.0      2009.0         6.0
710                  428.0  English    80.0      2004.0         6.3
3                   2701.0  English   250.0      2012.0         8.5
13                  1832.0  English   225.0      2006.0         7.3
767                  471.0  English    60.0      2014.0         7.8

      movie_facebook_likes      profit    genre_1    genre_2
0                    33000  523.505847     Action  Adventure
29                  150000  502.177271     Action  Adventure
26                   26000  458.672302      Drama    Romance
3024                 33000  449.935665     Action  Adventure
3080                 34000  424.449459     Family     Sci-Fi
794                 123000  403.279547     Action  Adventure
509                  17000  377.783777  Adventure  Animation
240                  13000  359.544677     Action  Adventure
66                   37000  348.316061     Action      Crime
439                 140000  329.999255  Adventure      Drama
812                 117000  305.024263     Action  Adventure
186                  82000  294.645577  Adventure     Sci-Fi
697                  19000  293.784000  Adventure     Sci-Fi
521                  56000  292.049635  Animation     Comedy
814                 112000  291.323553     Action  Biography
338                  11000  286.838870  Adventure  Animation
582                      0  286.471036  Adventure  Animation
339                  16000  283.019252     Action  Adventure
1536                 14000  276.625409     Action  Adventure
836                  59000  274.691196     Comedy      Drama
2051                 17000  272.158751     Action  Adventure
2601                 20000  267.761243     Comedy     Family
236                  10000  267.262555     Action  Adventure
161                   5000  264.706375     Action  Adventure
563                  70000  262.029560     Action  Animation
1181                 14000  253.501675      Drama    Mystery
2917                 21000  252.000000  Adventure      Drama
125                  58000  250.736600  Adventure  Animation
519                  36000  248.505540  Animation     Comedy
926                  13000  246.623634  Adventure      Drama
340                  10000  246.478898     Action  Adventure
1397                 24000  242.313371     Comedy     Comedy
3737                  5000  236.437427     Comedy     Family
631                  29000  232.523113  Adventure      Drama
522                  16000  231.124059     Action  Adventure
1403                 38000  226.950375  Biography      Drama
2152                 16000  224.374454     Action  Adventure
270                  21000  220.837577     Action  Adventure
2600                     0  220.760500     Action     Comedy
1400                 12000  216.188924     Action  Adventure
43                   30000  214.984497  Adventure  Animation
207                  52000  212.103873  Adventure     Sci-Fi
32                   95000  208.992272     Action  Adventure
8                   118000  208.991599     Action  Adventure
927                      0  207.652016  Adventure  Animation
36                       0  202.076689     Action  Adventure
710                      0  199.167575     Comedy    Romance
3                   164000  198.130642     Action   Thriller
13                    5000  198.032628     Action  Adventure
767                  64000  197.756197     Action  Adventure

In [359]:
# We will create a new variable movies_by_segmentto represent the grouping of movies dataframe by 'genre_1'
# and genre_2
movies_by_segment = movies.groupby(['genre_1', 'genre_2'])

In [360]:
# As per the subtask requirement, we will now obtain the Top 5 most popular genre_1 + genre_2 Combo 
# For this we will find the mean of gross values for each 'genre_1' and 'genre_2' combo, sort the values
# and the the top 5 Combo using head() function
PopGenre =  movies_by_segment['gross'].mean().sort_values(ascending=False).head(5)
print(PopGenre)

# As you can see below Family + Sci-Fi is the most popular combo of genres.

genre_1    genre_2
Family     Sci-Fi       434.949459
Adventure  Sci-Fi       228.627758
           Family       118.919540
           Animation    116.998550
Action     Adventure    109.595465
Name: gross, dtype: float64

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [361]:
# Code for creating Meryl_Streep data frame
# We need to find all movies in which 'Meryl Streep' was the lead. The lead actor is the value represented 
# by actor_1_name column
Meryl_Streep =  movies.loc[movies['actor_1_name'] == 'Meryl Streep']
print(Meryl_Streep.head(10))

       director_name  num_critic_for_reviews       gross  \
1408   David Frankel                   208.0  124.732962
1575  Sydney Pollack                    66.0   87.100000
1204     Nora Ephron                   252.0   94.125426
1618   David Frankel                   234.0   63.536011
410     Nancy Meyers                   187.0  112.703470
2781  Phyllida Lloyd                   331.0   29.959436
1925  Stephen Daldry                   174.0   41.597830
3135   Robert Altman                   211.0   20.338609
1106   Curtis Hanson                    42.0   46.815748
1674   Carl Franklin                    64.0   23.209440

                               genres  actor_1_name  \
1408             Comedy|Drama|Romance  Meryl Streep
1575          Biography|Drama|Romance  Meryl Streep
1204          Biography|Drama|Romance  Meryl Streep
1618             Comedy|Drama|Romance  Meryl Streep
410              Comedy|Drama|Romance  Meryl Streep
2781          Biography|Drama|History  Meryl Streep
1925                    Drama|Romance  Meryl Streep
3135               Comedy|Drama|Music  Meryl Streep
1106  Action|Adventure|Crime|Thriller  Meryl Streep
1674                            Drama  Meryl Streep

                     movie_title  num_voted_users  num_user_for_reviews  \
1408     The Devil Wears PradaÂ            286178                 631.0
1575             Out of AfricaÂ             52339                 200.0
1204             Julie & JuliaÂ             79264                 277.0
1618              Hope SpringsÂ             34258                 178.0
410           It's ComplicatedÂ             69860                 214.0
2781             The Iron LadyÂ             82327                 350.0
1925                 The HoursÂ            102123                 660.0
3135  A Prairie Home CompanionÂ             19655                 280.0
1106            The River WildÂ             32544                  69.0
1674            One True ThingÂ              9283                 112.0

     language  budget  title_year  imdb_score  movie_facebook_likes  \
1408  English    35.0      2006.0         6.8                     0
1575  English    31.0      1985.0         7.2                     0
1204  English    40.0      2009.0         7.0                 13000
1618  English    30.0      2012.0         6.3                     0
410   English    85.0      2009.0         6.6                     0
2781  English    13.0      2011.0         6.4                 18000
1925  English    25.0      2002.0         7.6                     0
3135  English    10.0      2006.0         6.8                   683
1106  English    45.0      1994.0         6.3                     0
1674  English    30.0      1998.0         7.0                   592

         profit    genre_1    genre_2
1408  89.732962     Comedy      Drama
1575  56.100000  Biography      Drama
1204  54.125426  Biography      Drama
1618  33.536011     Comedy      Drama
410   27.703470     Comedy      Drama
2781  16.959436  Biography      Drama
1925  16.597830      Drama    Romance
3135  10.338609     Comedy      Drama
1106   1.815748     Action  Adventure
1674  -6.790560      Drama      Drama

In [362]:
# Code for creating Leo_Caprio data frame
# We need to find all movies in which 'Leonardo DiCaprio' was the lead. The lead actor is the value represented 
# by 'actor_1_name' column

Leo_Caprio = movies.loc[movies['actor_1_name'] == 'Leonardo DiCaprio']
print(Leo_Caprio.head(10))

                director_name  num_critic_for_reviews       gross  \
26              James Cameron                   315.0  658.672302
97          Christopher Nolan                   642.0  292.568851
911          Steven Spielberg                   194.0  164.435221
296         Quentin Tarantino                   765.0  162.804648
179   Alejandro G. IÃ±Ã¡rritu                   556.0  183.635922
452           Martin Scorsese                   490.0  127.968405
361           Martin Scorsese                   352.0  132.373442
50               Baz Luhrmann                   490.0  144.812796
3476             Baz Luhrmann                   490.0  144.812796
2757             Baz Luhrmann                   106.0   46.338728

                                genres       actor_1_name  \
26                       Drama|Romance  Leonardo DiCaprio
97    Action|Adventure|Sci-Fi|Thriller  Leonardo DiCaprio
911              Biography|Crime|Drama  Leonardo DiCaprio
296                      Drama|Western  Leonardo DiCaprio
179   Adventure|Drama|Thriller|Western  Leonardo DiCaprio
452                   Mystery|Thriller  Leonardo DiCaprio
361               Crime|Drama|Thriller  Leonardo DiCaprio
50                       Drama|Romance  Leonardo DiCaprio
3476                     Drama|Romance  Leonardo DiCaprio
2757                     Drama|Romance  Leonardo DiCaprio

                movie_title  num_voted_users  num_user_for_reviews language  \
26                TitanicÂ            793059                2528.0  English
97              InceptionÂ           1468200                2803.0  English
911   Catch Me If You CanÂ            525801                 667.0  English
296      Django UnchainedÂ            955174                1193.0  English
179          The RevenantÂ            406020                1188.0  English
452        Shutter IslandÂ            786092                 964.0  English
361          The DepartedÂ            873649                2054.0  English
50       The Great GatsbyÂ            362912                 753.0  English
3476     The Great GatsbyÂ            362933                 753.0  English
2757       Romeo + JulietÂ            167750                 506.0  English

      budget  title_year  imdb_score  movie_facebook_likes      profit  \
26     200.0      1997.0         7.7                 26000  458.672302
97     160.0      2010.0         8.8                175000  132.568851
911     52.0      2002.0         8.0                 15000  112.435221
296    100.0      2012.0         8.5                199000   62.804648
179    135.0      2015.0         8.1                190000   48.635922
452     80.0      2010.0         8.1                 53000   47.968405
361     90.0      2006.0         8.5                 29000   42.373442
50     105.0      2013.0         7.3                115000   39.812796
3476   105.0      2013.0         7.3                115000   39.812796
2757    14.5      1996.0         6.8                 10000   31.838728

        genre_1    genre_2
26        Drama    Romance
97       Action  Adventure
911   Biography      Crime
296       Drama    Western
179   Adventure      Drama
452     Mystery   Thriller
361       Crime      Drama
50        Drama    Romance
3476      Drama    Romance
2757      Drama    Romance

In [363]:
# Code for creating Leo_Caprio data frame
# We need to find all movies in which 'Brad Pitt' was the lead. The lead actor is the value represented 
# by 'actor_1_name' column
Brad_Pitt = movies.loc[movies['actor_1_name'] == 'Brad Pitt'] 
print(Brad_Pitt.head(10))

                director_name  num_critic_for_reviews       gross  \
400         Steven Soderbergh                   186.0  183.405771
255                Doug Liman                   233.0  186.336103
940               Neil Jordan                   120.0  105.264608
470                David Ayer                   406.0   85.707116
254         Steven Soderbergh                   198.0  125.531634
2204  Alejandro G. IÃ±Ã¡rritu                   285.0   34.300771
2682           Andrew Dominik                   414.0   14.938570
2898               Tony Scott                   122.0   12.281500
2333      Angelina Jolie Pitt                   131.0    0.531009
1490          Terrence Malick                   584.0   13.303319

                                    genres actor_1_name  \
400                         Crime|Thriller    Brad Pitt
255   Action|Comedy|Crime|Romance|Thriller    Brad Pitt
940                   Drama|Fantasy|Horror    Brad Pitt
470                       Action|Drama|War    Brad Pitt
254                         Crime|Thriller    Brad Pitt
2204                                 Drama    Brad Pitt
2682                        Crime|Thriller    Brad Pitt
2898   Action|Crime|Drama|Romance|Thriller    Brad Pitt
2333                         Drama|Romance    Brad Pitt
1490                         Drama|Fantasy    Brad Pitt

                                            movie_title  num_voted_users  \
400                                    Ocean's ElevenÂ            402645
255                                  Mr. & Mrs. SmithÂ            348861
940   Interview with the Vampire: The Vampire Chroni...           239752
470                                              FuryÂ            303185
254                                    Ocean's TwelveÂ            284852
2204                                            BabelÂ            243799
2682                              Killing Them SoftlyÂ            111625
2898                                     True RomanceÂ            163492
2333                                       By the SeaÂ              7976
1490                                 The Tree of LifeÂ            136367

      num_user_for_reviews language  budget  title_year  imdb_score  \
400                  845.0  English    85.0      2001.0         7.8
255                  798.0  English   120.0      2005.0         6.5
940                  406.0  English    60.0      1994.0         7.6
470                  701.0  English    68.0      2014.0         7.6
254                  627.0  English   110.0      2004.0         6.4
2204                 908.0  English    25.0      2006.0         7.5
2682                 369.0  English    15.0      2012.0         6.2
2898                 460.0  English    13.0      1993.0         8.0
2333                  61.0  English    10.0      2015.0         5.3
1490                 975.0  English    32.0      2011.0         6.7

      movie_facebook_likes     profit genre_1   genre_2
400                      0  98.405771   Crime  Thriller
255                      0  66.336103  Action    Comedy
940                  11000  45.264608   Drama   Fantasy
470                  82000  17.707116  Action     Drama
254                      0  15.531634   Crime  Thriller
2204                     0   9.300771   Drama     Drama
2682                 20000  -0.061430   Crime  Thriller
2898                 15000  -0.718500  Action     Crime
2333                     0  -9.468991   Drama   Romance
1490                 39000 -18.696681   Drama   Fantasy

In [364]:
# Code for combining the three dataframes here
# We will now combined the obtained above three data frames to get a new data frame 'Combined'
# We will use the append function to append the values of each actor one after another.
Combined = (Meryl_Streep.append(Leo_Caprio)).append(Brad_Pitt )
print(Combined.head(20))

                director_name  num_critic_for_reviews       gross  \
1408            David Frankel                   208.0  124.732962
1575           Sydney Pollack                    66.0   87.100000
1204              Nora Ephron                   252.0   94.125426
1618            David Frankel                   234.0   63.536011
410              Nancy Meyers                   187.0  112.703470
2781           Phyllida Lloyd                   331.0   29.959436
1925           Stephen Daldry                   174.0   41.597830
3135            Robert Altman                   211.0   20.338609
1106            Curtis Hanson                    42.0   46.815748
1674            Carl Franklin                    64.0   23.209440
1483           Robert Redford                   227.0   14.998070
26              James Cameron                   315.0  658.672302
97          Christopher Nolan                   642.0  292.568851
911          Steven Spielberg                   194.0  164.435221
296         Quentin Tarantino                   765.0  162.804648
179   Alejandro G. IÃ±Ã¡rritu                   556.0  183.635922
452           Martin Scorsese                   490.0  127.968405
361           Martin Scorsese                   352.0  132.373442
50               Baz Luhrmann                   490.0  144.812796
3476             Baz Luhrmann                   490.0  144.812796

                                genres       actor_1_name  \
1408              Comedy|Drama|Romance       Meryl Streep
1575           Biography|Drama|Romance       Meryl Streep
1204           Biography|Drama|Romance       Meryl Streep
1618              Comedy|Drama|Romance       Meryl Streep
410               Comedy|Drama|Romance       Meryl Streep
2781           Biography|Drama|History       Meryl Streep
1925                     Drama|Romance       Meryl Streep
3135                Comedy|Drama|Music       Meryl Streep
1106   Action|Adventure|Crime|Thriller       Meryl Streep
1674                             Drama       Meryl Streep
1483                Drama|Thriller|War       Meryl Streep
26                       Drama|Romance  Leonardo DiCaprio
97    Action|Adventure|Sci-Fi|Thriller  Leonardo DiCaprio
911              Biography|Crime|Drama  Leonardo DiCaprio
296                      Drama|Western  Leonardo DiCaprio
179   Adventure|Drama|Thriller|Western  Leonardo DiCaprio
452                   Mystery|Thriller  Leonardo DiCaprio
361               Crime|Drama|Thriller  Leonardo DiCaprio
50                       Drama|Romance  Leonardo DiCaprio
3476                     Drama|Romance  Leonardo DiCaprio

                     movie_title  num_voted_users  num_user_for_reviews  \
1408     The Devil Wears PradaÂ            286178                 631.0
1575             Out of AfricaÂ             52339                 200.0
1204             Julie & JuliaÂ             79264                 277.0
1618              Hope SpringsÂ             34258                 178.0
410           It's ComplicatedÂ             69860                 214.0
2781             The Iron LadyÂ             82327                 350.0
1925                 The HoursÂ            102123                 660.0
3135  A Prairie Home CompanionÂ             19655                 280.0
1106            The River WildÂ             32544                  69.0
1674            One True ThingÂ              9283                 112.0
1483           Lions for LambsÂ             41170                 298.0
26                     TitanicÂ            793059                2528.0
97                   InceptionÂ           1468200                2803.0
911        Catch Me If You CanÂ            525801                 667.0
296           Django UnchainedÂ            955174                1193.0
179               The RevenantÂ            406020                1188.0
452             Shutter IslandÂ            786092                 964.0
361               The DepartedÂ            873649                2054.0
50            The Great GatsbyÂ            362912                 753.0
3476          The Great GatsbyÂ            362933                 753.0

     language  budget  title_year  imdb_score  movie_facebook_likes  \
1408  English    35.0      2006.0         6.8                     0
1575  English    31.0      1985.0         7.2                     0
1204  English    40.0      2009.0         7.0                 13000
1618  English    30.0      2012.0         6.3                     0
410   English    85.0      2009.0         6.6                     0
2781  English    13.0      2011.0         6.4                 18000
1925  English    25.0      2002.0         7.6                     0
3135  English    10.0      2006.0         6.8                   683
1106  English    45.0      1994.0         6.3                     0
1674  English    30.0      1998.0         7.0                   592
1483  English    35.0      2007.0         6.2                     0
26    English   200.0      1997.0         7.7                 26000
97    English   160.0      2010.0         8.8                175000
911   English    52.0      2002.0         8.0                 15000
296   English   100.0      2012.0         8.5                199000
179   English   135.0      2015.0         8.1                190000
452   English    80.0      2010.0         8.1                 53000
361   English    90.0      2006.0         8.5                 29000
50    English   105.0      2013.0         7.3                115000
3476  English   105.0      2013.0         7.3                115000

          profit    genre_1    genre_2
1408   89.732962     Comedy      Drama
1575   56.100000  Biography      Drama
1204   54.125426  Biography      Drama
1618   33.536011     Comedy      Drama
410    27.703470     Comedy      Drama
2781   16.959436  Biography      Drama
1925   16.597830      Drama    Romance
3135   10.338609     Comedy      Drama
1106    1.815748     Action  Adventure
1674   -6.790560      Drama      Drama
1483  -20.001930      Drama   Thriller
26    458.672302      Drama    Romance
97    132.568851     Action  Adventure
911   112.435221  Biography      Crime
296    62.804648      Drama    Western
179    48.635922  Adventure      Drama
452    47.968405    Mystery   Thriller
361    42.373442      Crime      Drama
50     39.812796      Drama    Romance
3476   39.812796      Drama    Romance

In [335]:
# Code for grouping the combined dataframe by 'actor_1_name'
# We will use groupby function to obtain this and assign it to variable 'groupby_1_name' 
groupby_1_name = Combined.groupby('actor_1_name')

In [336]:
# Code for finding the mean of critic reviews and audience reviews here

# Now using the above groupby result we will find the mean of num of critic reviews and assign it to 
#'mean_num_critic_reviews'
mean_num_critic_reviews = groupby_1_name.num_critic_for_reviews.mean() 

# Similarly, using the groupby result we will find the mean of num of user reviews and assign it to 
#'mean_num_user_reviews'
mean_num_user_reviews = groupby_1_name.num_user_for_reviews.mean() 

# Now, after sorting the values based on critical reviews we will try to obtain the actor name with 
# highest mean value of critic reviews
actor_highest_num_critic_reviews = mean_num_critic_reviews.sort_values(ascending=False).index[0]

# Now, after sorting the values based on user reviews we will try to obtain the actor name with 
# highest mean value of user reviews
actor_highest_num_user_reviews = mean_num_user_reviews.sort_values(ascending=False).index[0]

print(actor_highest_num_critic_reviews)
print(actor_highest_num_user_reviews)

# As you can see below Leonardo Di Caprio tops both the lists.

Leonardo DiCaprio
Leonardo DiCaprio

**Checkpoint 6:** `Leonardo` has aced both the lists!