In [1]:
import numpy as np
import pandas as pd

In [117]:
companies =  pd.read_csv("companies.txt", sep=None, encoding="ISO-8859-1",engine='python')

print(companies.head())
print(companies.shape)
print(companies.info())
print(companies.isnull().sum());
companies.permalink= companies.permalink.str.encode('utf-8').str.decode('ascii', 'ignore')
companies.permalink = companies.permalink.str.upper()
print(companies.head())
print(companies.shape)
print(companies.info())
print(companies.isnull().sum());

# 66368 companies,66368 companies ,permalink,no,114949,16

                             permalink                    name  \
0                  /Organization/-Fame                   #fame
1               /Organization/-Qounter                :Qounter
2  /Organization/-The-One-Of-Them-Inc-  (THE) ONE of THEM,Inc.
3                /Organization/0-6-Com                 0-6.com
4       /Organization/004-Technologies        004 Technologies

                        homepage_url  \
0                 http://livfame.com
1             http://www.qounter.com
2                http://oneofthem.jp
3                 http://www.0-6.com
4  http://004gmbh.de/en/004-interact

                                       category_list     status country_code  \
0                                              Media  operating          IND
1  Application Platforms|Real Time|Social Network...  operating          USA
2                                  Apps|Games|Mobile  operating          NaN
3                                        Curated Web  operating          CHN
4                                           Software  operating          USA

  state_code                 region           city  founded_at
0         16                 Mumbai         Mumbai         NaN
1         DE             DE - Other  Delaware City  04-09-2014
2        NaN                    NaN            NaN         NaN
3         22                Beijing        Beijing  01-01-2007
4         IL  Springfield, Illinois      Champaign  01-01-2010
(66368, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66368 entries, 0 to 66367
Data columns (total 10 columns):
permalink        66368 non-null object
name             66367 non-null object
homepage_url     61310 non-null object
category_list    63220 non-null object
status           66368 non-null object
country_code     59410 non-null object
state_code       57821 non-null object
region           58338 non-null object
city             58340 non-null object
founded_at       51147 non-null object
dtypes: object(10)
memory usage: 5.1+ MB
None
permalink            0
name                 1
homepage_url      5058
category_list     3148
status               0
country_code      6958
state_code        8547
region            8030
city              8028
founded_at       15221
dtype: int64
                             permalink                    name  \
0                  /ORGANIZATION/-FAME                   #fame
1               /ORGANIZATION/-QOUNTER                :Qounter
2  /ORGANIZATION/-THE-ONE-OF-THEM-INC-  (THE) ONE of THEM,Inc.
3                /ORGANIZATION/0-6-COM                 0-6.com
4       /ORGANIZATION/004-TECHNOLOGIES        004 Technologies

                        homepage_url  \
0                 http://livfame.com
1             http://www.qounter.com
2                http://oneofthem.jp
3                 http://www.0-6.com
4  http://004gmbh.de/en/004-interact

                                       category_list     status country_code  \
0                                              Media  operating          IND
1  Application Platforms|Real Time|Social Network...  operating          USA
2                                  Apps|Games|Mobile  operating          NaN
3                                        Curated Web  operating          CHN
4                                           Software  operating          USA

  state_code                 region           city  founded_at
0         16                 Mumbai         Mumbai         NaN
1         DE             DE - Other  Delaware City  04-09-2014
2        NaN                    NaN            NaN         NaN
3         22                Beijing        Beijing  01-01-2007
4         IL  Springfield, Illinois      Champaign  01-01-2010
(66368, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66368 entries, 0 to 66367
Data columns (total 10 columns):
permalink        66368 non-null object
name             66367 non-null object
homepage_url     61310 non-null object
category_list    63220 non-null object
status           66368 non-null object
country_code     59410 non-null object
state_code       57821 non-null object
region           58338 non-null object
city             58340 non-null object
founded_at       51147 non-null object
dtypes: object(10)
memory usage: 5.1+ MB
None
permalink            0
name                 1
homepage_url      5058
category_list     3148
status               0
country_code      6958
state_code        8547
region            8030
city              8028
founded_at       15221
dtype: int64

In [118]:
rounds2 =  pd.read_csv("rounds2.csv", sep=None, encoding="ISO-8859-1",engine='python')
rounds2.company_permalink= rounds2.company_permalink.str.encode('utf-8').str.decode('ascii', 'ignore').str.upper()
print(rounds2.head());
print(rounds2.info())
rounds2.to_csv("data_modified_permalink.csv")

                     company_permalink  \
0                  /ORGANIZATION/-FAME
1               /ORGANIZATION/-QOUNTER
2               /ORGANIZATION/-QOUNTER
3  /ORGANIZATION/-THE-ONE-OF-THEM-INC-
4                /ORGANIZATION/0-6-COM

                           funding_round_permalink funding_round_type  \
0  /funding-round/9a01d05418af9f794eebff7ace91f638            venture
1  /funding-round/22dacff496eb7acb2b901dec1dfe5633            venture
2  /funding-round/b44fbb94153f6cdef13083530bb48030               seed
3  /funding-round/650b8f704416801069bb178a1418776b            venture
4  /funding-round/5727accaeaa57461bd22a9bdd945382d            venture

  funding_round_code   funded_at  raised_amount_usd
0                  B  05-01-2015         10000000.0
1                  A  14-10-2014                NaN
2                NaN  01-03-2014           700000.0
3                  B  30-01-2014          3406878.0
4                  A  19-03-2008          2000000.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114949 entries, 0 to 114948
Data columns (total 6 columns):
company_permalink          114949 non-null object
funding_round_permalink    114949 non-null object
funding_round_type         114949 non-null object
funding_round_code         31140 non-null object
funded_at                  114949 non-null object
raised_amount_usd          94959 non-null float64
dtypes: float64(1), object(5)
memory usage: 5.3+ MB
None

In [128]:
#print(rounds2.head())
#print(rounds2.shape)
#print(rounds2.info())
#print(rounds2.isnull().sum());

rounds2_group_by = rounds2.groupby(by=['company_permalink'],as_index=False)
print(rounds2_group_by)

df = pd.DataFrame(rounds2_group_by.size()).reset_index()
print(df.info())
print(df.head(50))
print(df.shape)
output = companies.permalink.isin(df.company_permalink)  
print(output.value_counts())

<pandas.core.groupby.groupby.DataFrameGroupBy object at 0x12d81fac8>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66368 entries, 0 to 66367
Data columns (total 2 columns):
company_permalink    66368 non-null object
0                    66368 non-null int64
dtypes: int64(1), object(1)
memory usage: 1.0+ MB
None
                           company_permalink  0
0                        /ORGANIZATION/-FAME  1
1                     /ORGANIZATION/-QOUNTER  2
2        /ORGANIZATION/-THE-ONE-OF-THEM-INC-  1
3                      /ORGANIZATION/0-6-COM  1
4             /ORGANIZATION/004-TECHNOLOGIES  1
5           /ORGANIZATION/01GAMES-TECHNOLOGY  1
6        /ORGANIZATION/0NDINE-BIOMEDICAL-INC  2
7                       /ORGANIZATION/0XDATA  4
8                            /ORGANIZATION/1  3
9                  /ORGANIZATION/1-2-3-LISTO  1
10                     /ORGANIZATION/1-4-ALL  1
11            /ORGANIZATION/1-618-TECHNOLOGY  1
12               /ORGANIZATION/1-800-DENTIST  1
13               /ORGANIZATION/1-800-DOCTORS  1
14  /ORGANIZATION/1-800-PUBLICRELATIONS-INC-  1
15                /ORGANIZATION/1-MAINSTREAM  1
16                     /ORGANIZATION/1-OF-99  1
17                 /ORGANIZATION/10-20-MEDIA  4
18             /ORGANIZATION/10-MINUTES-WITH  2
19                  /ORGANIZATION/1000-CORKS  1
20                /ORGANIZATION/1000-MARKETS  1
21                     /ORGANIZATION/1000CHI  1
22                   /ORGANIZATION/1000LOOKZ  1
23                /ORGANIZATION/1000MEMORIES  2
24             /ORGANIZATION/1000MUSEUMS-COM  9
25                  /ORGANIZATION/1001-MENUS  5
26          /ORGANIZATION/1001PHARMACIES-COM  1
27                     /ORGANIZATION/1006-TV  3
28                    /ORGANIZATION/100DU-TV  2
29                    /ORGANIZATION/100E-COM  2
30                   /ORGANIZATION/100HEALTH  2
31                     /ORGANIZATION/100PLUS  2
32                    /ORGANIZATION/1010DATA  1
33                     /ORGANIZATION/10ALIKE  2
34                /ORGANIZATION/10BESTTHINGS  1
35                       /ORGANIZATION/10K-2  1
36                     /ORGANIZATION/10NORTH  1
37                       /ORGANIZATION/10SEC  2
38          /ORGANIZATION/10SECONDS-SOFTWARE  1
39                       /ORGANIZATION/10SIX  1
40                  /ORGANIZATION/10TRACKS-2  2
41                /ORGANIZATION/10X-GENOMICS  1
42            /ORGANIZATION/10X-TECHNOLOGIES  2
43                  /ORGANIZATION/10X10-ROOM  1
44                   /ORGANIZATION/11-HEALTH  1
45           /ORGANIZATION/115-NETWORK-DISKS  1
46                       /ORGANIZATION/117GO  1
47               /ORGANIZATION/11I-SOLUTIONS  1
48                     /ORGANIZATION/12-LABS  1
49            /ORGANIZATION/12-STAR-SURVIVAL  1
(66368, 2)
True    66368
Name: permalink, dtype: int64

In [298]:
master_frame = pd.merge(rounds2,companies,how='left', 
                        left_on=['company_permalink'], right_on=['permalink'])
print(master_frame.shape)
print(master_frame.info())
print(master_frame.head())

(114949, 16)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 114949 entries, 0 to 114948
Data columns (total 16 columns):
company_permalink          114949 non-null object
funding_round_permalink    114949 non-null object
funding_round_type         114949 non-null object
funding_round_code         31140 non-null object
funded_at                  114949 non-null object
raised_amount_usd          94959 non-null float64
permalink                  114949 non-null object
name                       114948 non-null object
homepage_url               108815 non-null object
category_list              111539 non-null object
status                     114949 non-null object
country_code               106271 non-null object
state_code                 104003 non-null object
region                     104782 non-null object
city                       104785 non-null object
founded_at                 94428 non-null object
dtypes: float64(1), object(15)
memory usage: 14.9+ MB
None
                     company_permalink  \
0                  /ORGANIZATION/-FAME
1               /ORGANIZATION/-QOUNTER
2               /ORGANIZATION/-QOUNTER
3  /ORGANIZATION/-THE-ONE-OF-THEM-INC-
4                /ORGANIZATION/0-6-COM

                           funding_round_permalink funding_round_type  \
0  /funding-round/9a01d05418af9f794eebff7ace91f638            venture
1  /funding-round/22dacff496eb7acb2b901dec1dfe5633            venture
2  /funding-round/b44fbb94153f6cdef13083530bb48030               seed
3  /funding-round/650b8f704416801069bb178a1418776b            venture
4  /funding-round/5727accaeaa57461bd22a9bdd945382d            venture

  funding_round_code   funded_at  raised_amount_usd  \
0                  B  05-01-2015        10000000.00
1                  A  14-10-2014                nan
2                NaN  01-03-2014          700000.00
3                  B  30-01-2014         3406878.00
4                  A  19-03-2008         2000000.00

                             permalink                    name  \
0                  /ORGANIZATION/-FAME                   #fame
1               /ORGANIZATION/-QOUNTER                :Qounter
2               /ORGANIZATION/-QOUNTER                :Qounter
3  /ORGANIZATION/-THE-ONE-OF-THEM-INC-  (THE) ONE of THEM,Inc.
4                /ORGANIZATION/0-6-COM                 0-6.com

             homepage_url                                      category_list  \
0      http://livfame.com                                              Media
1  http://www.qounter.com  Application Platforms|Real Time|Social Network...
2  http://www.qounter.com  Application Platforms|Real Time|Social Network...
3     http://oneofthem.jp                                  Apps|Games|Mobile
4      http://www.0-6.com                                        Curated Web

      status country_code state_code      region           city  founded_at
0  operating          IND         16      Mumbai         Mumbai         NaN
1  operating          USA         DE  DE - Other  Delaware City  04-09-2014
2  operating          USA         DE  DE - Other  Delaware City  04-09-2014
3  operating          NaN        NaN         NaN            NaN         NaN
4  operating          CHN         22     Beijing        Beijing  01-01-2007

In [299]:
print(round(100*(master_frame.isnull().sum()/len(master_frame.index)), 2))
master_frame.drop(df.columns[['funding_round_code', 'founded_at', 'homepage_url', 'state_code', 
    'region', 'city']], axis=1, inplace=True)
print(round(100*(master_frame.isnull().sum()/len(master_frame.index)), 2))

company_permalink          0.00
funding_round_permalink    0.00
funding_round_type         0.00
funding_round_code        72.91
funded_at                  0.00
raised_amount_usd         17.39
permalink                  0.00
name                       0.00
homepage_url               5.34
category_list              2.97
status                     0.00
country_code               7.55
state_code                 9.52
region                     8.84
city                       8.84
founded_at                17.85
dtype: float64
company_permalink          0.00
funding_round_permalink    0.00
funding_round_type         0.00
funded_at                  0.00
raised_amount_usd         17.39
permalink                  0.00
name                       0.00
category_list              2.97
status                     0.00
country_code               7.55
dtype: float64

In [344]:
print('No. of columns in master frame :',master_frame.shape[1])

# Check if any rows are completely null
print('No. of rows with all columns null in master frame:',len(master_frame[master_frame.isnull().sum(axis=1)==master_frame.shape[1]].index))

# Check if any row has mre than 3 columns null
print('No .of rows in master_frame with >3 columns as null :- ', len(master_frame[master_frame.isnull().sum(axis=1) > 3].index))

# Converting raised amount to mn as it is the required unit
master_frame['raised_amount_usd'] = master_frame['raised_amount_usd']/1000000

No. of columns in master frame : 10
No. of rows with all columns null in master frame: 0
No .of rows in master_frame with >3 columns as null :-  0

In [ ]:
# Category List has nulls
master_frame['category_list']=master_frame['category_list'].fillna("")

In [359]:
master_frame_groupby_funding_type = master_frame[(master_frame['funding_round_type']=='seed') | (master_frame['funding_round_type']=='venture')| (master_frame['funding_round_type']=='angel') | (master_frame['funding_round_type']=='private_equity')]  .groupby(by=['funding_round_type'])
avg_funding_for_each_round = pd.DataFrame(master_frame_groupby_funding_type['raised_amount_usd'].mean()).reset_index()
pd.set_option('display.float_format', '{:.2f}'.format)
print(avg_funding_for_each_round)
fund_type_5_to_15_million = avg_funding_for_each_round.funding_round_type[ (avg_funding_for_each_round.raised_amount_usd>5) & ((avg_funding_for_each_round.raised_amount_usd<15))]
print('The suitable funding round for investment would be :',fund_type_5_to_15_million)
# venture 11.75 mnUSD, seed - 0.72mn , angel - 0.96 mn, private_equity - 73.31 mn usd , venture

  funding_round_type  raised_amount_usd
0              angel               0.96
1     private_equity              73.31
2               seed               0.72
3            venture              11.75
The suitable funding round for investment would be : 3    venture
Name: funding_round_type, dtype: object

In [360]:
venture_data_frame = master_frame.loc[master_frame['funding_round_type'].isin(['venture']),:]
venture_data_frame.sort_values(by=['raised_amount_usd'],ascending=False,inplace=True)
countries_with_highest_funding = venture_data_frame['country_code'].dropna()
countries_with_highest_funding.drop_duplicates(keep='first',inplace=True);
print(type(countries_with_highest_funding))
top9 = countries_with_highest_funding[:9]
print(top9)
# USA ,India, GBR

<class 'pandas.core.series.Series'>
37569     USA
112173    CHN
36401     IND
92043     GBR
26904     NLD
93960     SWE
100384    FRA
41238     SGP
86308     NOR
Name: country_code, dtype: object

/Users/karandeepmalik/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [308]:
sector_mapping =  pd.read_csv("mapping.csv", encoding="ISO-8859-1") 
print(sector_mapping.head())
print(sector_mapping.info())
print(sector_mapping.shape)
category_main_sector_mapping = pd.DataFrame()
category_main_sector_mapping['sector'] =sector_mapping['category_list']
category_main_sector_mapping['main sector'] = sector_mapping.apply(lambda x: x.isin([1]), axis=1).apply(lambda x: list(sector_mapping.columns[x]), axis=1)
print(category_main_sector_mapping)

category_list_master_primary = master_frame['category_list'].dropna().apply(lambda x: x.split('|')[0])
print(category_list_data_frame )

   category_list  Automotive & Sports  Blanks  Cleantech / Semiconductors  \
0            NaN                    0       1                           0
1             3D                    0       0                           0
2    3D Printing                    0       0                           0
3  3D Technology                    0       0                           0
4     Accounting                    0       0                           0

   Entertainment  Health  Manufacturing  News, Search and Messaging  Others  \
0              0       0              0                           0       0
1              0       0              1                           0       0
2              0       0              1                           0       0
3              0       0              1                           0       0
4              0       0              0                           0       0

   Social, Finance, Analytics, Advertising
0                                        0
1                                        0
2                                        0
3                                        0
4                                        1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 688 entries, 0 to 687
Data columns (total 10 columns):
category_list                              687 non-null object
Automotive & Sports                        688 non-null int64
Blanks                                     688 non-null int64
Cleantech / Semiconductors                 688 non-null int64
Entertainment                              688 non-null int64
Health                                     688 non-null int64
Manufacturing                              688 non-null int64
News, Search and Messaging                 688 non-null int64
Others                                     688 non-null int64
Social, Finance, Analytics, Advertising    688 non-null int64
dtypes: int64(9), object(1)
memory usage: 53.8+ KB
None
(688, 10)
                         sector                                main sector
0                           NaN                                   [Blanks]
1                            3D                            [Manufacturing]
2                   3D Printing                            [Manufacturing]
3                 3D Technology                            [Manufacturing]
4                    Accounting  [Social, Finance, Analytics, Advertising]
5              Active Lifestyle                                   [Health]
6                  Ad Targeting  [Social, Finance, Analytics, Advertising]
7            Advanced Materials                            [Manufacturing]
8              Adventure Travel                      [Automotive & Sports]
9                   Advertising  [Social, Finance, Analytics, Advertising]
10        Advertising Exchanges  [Social, Finance, Analytics, Advertising]
11         Advertising Networks  [Social, Finance, Analytics, Advertising]
12        Advertising Platforms  [Social, Finance, Analytics, Advertising]
13                       Advice                                   [Others]
14                    Aerospace                      [Automotive & Sports]
15                  Agriculture                            [Manufacturing]
16        Air Pollution Control               [Cleantech / Semiconductors]
17                   Algorithms                                   [Others]
18                  All Markets                                   [Others]
19                 All Students                                   [Others]
20          Alter0tive Medicine                                   [Health]
21                       Alumni                                   [Others]
22                     A0lytics  [Social, Finance, Analytics, Advertising]
23                      Android  [Social, Finance, Analytics, Advertising]
24                       Angels                                   [Others]
25                  Animal Feed                                   [Health]
26   Anything Capital Intensive  [Social, Finance, Analytics, Advertising]
27                App Discovery               [News, Search and Messaging]
28                App Marketing               [News, Search and Messaging]
29                   App Stores               [News, Search and Messaging]
..                          ...                                        ...
658                   Usability                                   [Others]
659      User Experience Design                                   [Others]
660              User Interface                                   [Others]
661                   Utilities                                   [Others]
662     Vending and Concessions                                   [Others]
663             Venture Capital  [Social, Finance, Analytics, Advertising]
664                   Veteri0ry                                   [Health]
665                       Video                            [Entertainment]
666          Video Conferencing                            [Entertainment]
667                 Video Games                            [Entertainment]
668             Video on Demand                            [Entertainment]
669             Video Streaming                            [Entertainment]
670          Virtual Workforces                            [Entertainment]
671                        VoIP                            [Entertainment]
672             Waste Ma0gement               [Cleantech / Semiconductors]
673                       Watch                                   [Others]
674                       Water               [Cleantech / Semiconductors]
675          Water Purification               [Cleantech / Semiconductors]
676                   Wearables               [Cleantech / Semiconductors]
677                Web Browsers               [News, Search and Messaging]
678                  Web Design               [News, Search and Messaging]
679             Web Development                                   [Others]
680                 Web Hosting                                   [Others]
681                   Web Tools                                   [Others]
682                    Weddings                            [Entertainment]
683                   Wholesale                                   [Others]
684            Wine And Spirits                            [Entertainment]
685                    Wireless                            [Entertainment]
686                       Women                                   [Others]
687                Young Adults                                   [Others]

[688 rows x 2 columns]
0                         Media
1         Application Platforms
2         Application Platforms
3                          Apps
4                   Curated Web
5                      Software
6                         Games
7                 Biotechnology
8                 Biotechnology
9                     Analytics
10                    Analytics
11                    Analytics
12                    Analytics
13                       Mobile
14                       Mobile
15                       Mobile
16                   E-Commerce
17                Entertainment
18                   Networking
19          Health and Wellness
20          Health and Wellness
21           Internet Marketing
22                         Apps
23                Entertainment
24                   E-Commerce
25                   E-Commerce
26                   E-Commerce
27                   E-Commerce
28                    Education
29                    Education
                  ...
114919                 Software
114920            Biotechnology
114921            Biotechnology
114922            Biotechnology
114923            Biotechnology
114924          Cloud Computing
114925          Cloud Computing
114926    Public Transportation
114927    Public Transportation
114928            Biotechnology
114929            Biotechnology
114930            Biotechnology
114931            Biotechnology
114932               E-Commerce
114933               E-Commerce
114934               E-Commerce
114935               E-Commerce
114936            Biotechnology
114937            Biotechnology
114938                Analytics
114939                Analytics
114940                Analytics
114941      Enterprise Software
114942              Advertising
114943              Advertising
114944              Advertising
114945              Advertising
114946
114947     Consumer Electronics
114948           Consumer Goods
Name: category_list, Length: 114949, dtype: object

In [329]:
combined_master_category_list_master_primary = pd.DataFrame()
combined_master_category_list_master_primary = master_frame.copy(deep=True)
combined_master_category_list_master_primary['primary sector']= category_list_master_primary
print(combined_master_category_list_master_primary.head())

combined_master_primary_sector_main_sector = pd.merge(combined_master_category_list_master_primary,category_main_sector_mapping, 
           how='inner',left_on='primary sector',right_on='sector').sort_values(by=['permalink'])
print(combined_master_primary_sector_main_sector.head())

                     company_permalink  \
0                  /ORGANIZATION/-FAME
1               /ORGANIZATION/-QOUNTER
2               /ORGANIZATION/-QOUNTER
3  /ORGANIZATION/-THE-ONE-OF-THEM-INC-
4                /ORGANIZATION/0-6-COM

                           funding_round_permalink funding_round_type  \
0  /funding-round/9a01d05418af9f794eebff7ace91f638            venture
1  /funding-round/22dacff496eb7acb2b901dec1dfe5633            venture
2  /funding-round/b44fbb94153f6cdef13083530bb48030               seed
3  /funding-round/650b8f704416801069bb178a1418776b            venture
4  /funding-round/5727accaeaa57461bd22a9bdd945382d            venture

    funded_at  raised_amount_usd                            permalink  \
0  05-01-2015        10000000.00                  /ORGANIZATION/-FAME
1  14-10-2014                nan               /ORGANIZATION/-QOUNTER
2  01-03-2014          700000.00               /ORGANIZATION/-QOUNTER
3  30-01-2014         3406878.00  /ORGANIZATION/-THE-ONE-OF-THEM-INC-
4  19-03-2008         2000000.00                /ORGANIZATION/0-6-COM

                     name                                      category_list  \
0                   #fame                                              Media
1                :Qounter  Application Platforms|Real Time|Social Network...
2                :Qounter  Application Platforms|Real Time|Social Network...
3  (THE) ONE of THEM,Inc.                                  Apps|Games|Mobile
4                 0-6.com                                        Curated Web

      status country_code         primary sector
0  operating          IND                  Media
1  operating          USA  Application Platforms
2  operating          USA  Application Platforms
3  operating          NaN                   Apps
4  operating          CHN            Curated Web
                        company_permalink  \
0                     /ORGANIZATION/-FAME
300                /ORGANIZATION/-QOUNTER
299                /ORGANIZATION/-QOUNTER
639   /ORGANIZATION/-THE-ONE-OF-THEM-INC-
2965                /ORGANIZATION/0-6-COM

                              funding_round_permalink funding_round_type  \
0     /funding-round/9a01d05418af9f794eebff7ace91f638            venture
300   /funding-round/b44fbb94153f6cdef13083530bb48030               seed
299   /funding-round/22dacff496eb7acb2b901dec1dfe5633            venture
639   /funding-round/650b8f704416801069bb178a1418776b            venture
2965  /funding-round/5727accaeaa57461bd22a9bdd945382d            venture

       funded_at  raised_amount_usd                            permalink  \
0     05-01-2015        10000000.00                  /ORGANIZATION/-FAME
300   01-03-2014          700000.00               /ORGANIZATION/-QOUNTER
299   14-10-2014                nan               /ORGANIZATION/-QOUNTER
639   30-01-2014         3406878.00  /ORGANIZATION/-THE-ONE-OF-THEM-INC-
2965  19-03-2008         2000000.00                /ORGANIZATION/0-6-COM

                        name  \
0                      #fame
300                 :Qounter
299                 :Qounter
639   (THE) ONE of THEM,Inc.
2965                 0-6.com

                                          category_list     status  \
0                                                 Media  operating
300   Application Platforms|Real Time|Social Network...  operating
299   Application Platforms|Real Time|Social Network...  operating
639                                   Apps|Games|Mobile  operating
2965                                        Curated Web  operating

     country_code         primary sector                 sector  \
0             IND                  Media                  Media
300           USA  Application Platforms  Application Platforms
299           USA  Application Platforms  Application Platforms
639           NaN                   Apps                   Apps
2965          CHN            Curated Web            Curated Web

                       main sector
0                  [Entertainment]
300   [News, Search and Messaging]
299   [News, Search and Messaging]
639   [News, Search and Messaging]
2965  [News, Search and Messaging]
                              company_permalink  \
37307  /ORGANIZATION/1-800-PUBLICRELATIONS-INC-
640                  /ORGANIZATION/1-MAINSTREAM
58748              /ORGANIZATION/128-TECHNOLOGY
59326           /ORGANIZATION/1366-TECHNOLOGIES
59325           /ORGANIZATION/1366-TECHNOLOGIES

                               funding_round_permalink funding_round_type  \
37307  /funding-round/11c228f58831bc7ed337ef69ecc560c2     private_equity
640    /funding-round/b952cbaf401f310927430c97b68162ea            venture
58748  /funding-round/fb6216a30cb566ede89e0bee0623a634            venture
59326  /funding-round/6d3f3797371956ece035b8478c1441b2            venture
59325  /funding-round/424129ce1235cfab2655ee81305f7c2b            venture

        funded_at  raised_amount_usd  \
37307  01-02-2015         6000000.00
640    17-03-2015         5000000.00
58748  16-12-2014        11999347.00
59326  09-04-2015         5000000.00
59325  15-10-2013        15000000.00

                                      permalink                         name  \
37307  /ORGANIZATION/1-800-PUBLICRELATIONS-INC-  1-800-PublicRelations, Inc.
640                  /ORGANIZATION/1-MAINSTREAM                 1 Mainstream
58748              /ORGANIZATION/128-TECHNOLOGY               128 Technology
59326           /ORGANIZATION/1366-TECHNOLOGIES            1366 Technologies
59325           /ORGANIZATION/1366-TECHNOLOGIES            1366 Technologies

                                   category_list     status country_code  \
37307  Internet Marketing|Media|Public Relations  operating          USA
640             Apps|Cable|Distribution|Software   acquired          USA
58748               Service Providers|Technology  operating          USA
59326                              Manufacturing  operating          USA
59325                              Manufacturing  operating          USA

           primary sector              sector  \
37307  Internet Marketing  Internet Marketing
640                  Apps                Apps
58748   Service Providers   Service Providers
59326       Manufacturing       Manufacturing
59325       Manufacturing       Manufacturing

                                     main sector
37307  [Social, Finance, Analytics, Advertising]
640                 [News, Search and Messaging]
58748                                   [Others]
59326                            [Manufacturing]
59325                            [Manufacturing]

In [341]:
US_D1 = combined_master_primary_sector_main_sector.loc[(combined_master_primary_sector_main_sector.raised_amount_usd >= 5000000 ) &
                                                       (combined_master_primary_sector_main_sector.raised_amount_usd <= 15000000 )&
                                                       (combined_master_primary_sector_main_sector.country_code == 'USA')
                                                      ]
print(US_D1.head())

US_groupby_main_sector = US_D1.groupby(by=['main sector','raised_amount_usd'])
print(US_groupby_main_sector.raised_amount_usd.count())

                              company_permalink  \
37307  /ORGANIZATION/1-800-PUBLICRELATIONS-INC-
640                  /ORGANIZATION/1-MAINSTREAM
58748              /ORGANIZATION/128-TECHNOLOGY
59326           /ORGANIZATION/1366-TECHNOLOGIES
59325           /ORGANIZATION/1366-TECHNOLOGIES

                               funding_round_permalink funding_round_type  \
37307  /funding-round/11c228f58831bc7ed337ef69ecc560c2     private_equity
640    /funding-round/b952cbaf401f310927430c97b68162ea            venture
58748  /funding-round/fb6216a30cb566ede89e0bee0623a634            venture
59326  /funding-round/6d3f3797371956ece035b8478c1441b2            venture
59325  /funding-round/424129ce1235cfab2655ee81305f7c2b            venture

        funded_at  raised_amount_usd  \
37307  01-02-2015         6000000.00
640    17-03-2015         5000000.00
58748  16-12-2014        11999347.00
59326  09-04-2015         5000000.00
59325  15-10-2013        15000000.00

                                      permalink                         name  \
37307  /ORGANIZATION/1-800-PUBLICRELATIONS-INC-  1-800-PublicRelations, Inc.
640                  /ORGANIZATION/1-MAINSTREAM                 1 Mainstream
58748              /ORGANIZATION/128-TECHNOLOGY               128 Technology
59326           /ORGANIZATION/1366-TECHNOLOGIES            1366 Technologies
59325           /ORGANIZATION/1366-TECHNOLOGIES            1366 Technologies

                                   category_list     status country_code  \
37307  Internet Marketing|Media|Public Relations  operating          USA
640             Apps|Cable|Distribution|Software   acquired          USA
58748               Service Providers|Technology  operating          USA
59326                              Manufacturing  operating          USA
59325                              Manufacturing  operating          USA

           primary sector              sector  \
37307  Internet Marketing  Internet Marketing
640                  Apps                Apps
58748   Service Providers   Service Providers
59326       Manufacturing       Manufacturing
59325       Manufacturing       Manufacturing

                                     main sector
37307  [Social, Finance, Analytics, Advertising]
640                 [News, Search and Messaging]
58748                                   [Others]
59326                            [Manufacturing]
59325                            [Manufacturing]

TypeError: unhashable type: 'list'